# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Tour
    url: tour
    weight: 10
  - name: People
    url: people
    weight: 20
  - name: Publications
    url: publication
    weight: 30
  - name: Project
    url: project
    weight: 40
  - name: Software
    url: software
    weight: 50
  - name: News
    url: post
    weight: 60
  - name: Events
    url: event
    weight: 70
  - name: Contact
    url: contact
    weight: 80
  - name: CV
    url: uploads/cv.pdf
    weight: 90
  - name: 
    pre: "<i class=\"fab fa-github\" style=\"color: #333; font-size: 1rem; line-height: 1.25\"></i>"
    url: "https://github.com/prashjha/"
    external: true
    weight: 100